# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install bundler
  - bundle install
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/pietrocaselani/Hangman.git"
script:
  - bundle exec fastlane travis
after_success:
  - bundle exec fastlane push
  - bash <(curl -s https://codecov.io/bash)
