COMMIT_MESSAGE = "Bump podspec to"

lane :pods do
	cocoapods(podfile: "Example/")
end

lane :tests do
	scan(workspace: "Example/Hangman.xcworkspace", scheme: "Hangman-Example", clean: true, devices: ["iPhone 5"])
end

lane :travis do
	pods
	tests
	pod_lib_lint(allow_warnings: false, verbose: false)
end

lane :push do
	version = version_bump_podspec(path: "Hangman.podspec")
	git_commit(path: ["./Hangman.podspec", "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
	changelog = changelog_from_git_commits
	github_release = set_github_release(
		repository_name: "pietrocaselani/Hangman",
		api_token: ENV['GITHUB_TOKEN'],
		name: version,
		tag_name: version,
		description: changelog,
		commitish: "master"
	)
	sh("git fetch --tags")
	push_to_git_remote(remote_branch: 'master', force: false, tags: true)
	pod_push(allow_warnings: false, verbose: true)
end
